const { Router } = require("express");
const router = Router();
// const checkAuthAdmin = require("../../middleware/check-auth-admin");
const checkAuthAdmin = require("../../middleware/check-auth");
const checkAuth = require("../../middleware/check-auth");

var controllerCliente = require("../controllers/ControllerCliente");
var controllerCobertura = require("../controllers/ControllerCobertura");
var controllerTamano = require("../controllers/ControllerTamano");
var controllerEstado = require("../controllers/ControllerEstado");
var controllerSabor = require("../controllers/ControllerSabor");
var controllerPedido = require("../controllers/ControllerPedido");
var controllerProducto = require("../controllers/ControllerProducto");
var controllerAdmin = require("../controllers/ControllerAdmin");
var controllerEmail = require('../controllers/ControllerEmail');

router.get("/", controllerCliente.home);
router.post("/crearCliente", controllerCliente.crearCliente);
router.get("/clientes", checkAuthAdmin, controllerCliente.consultarClientes);
router.get("/cliente/:id", checkAuthAdmin, controllerCliente.consultarCliente);
router.post("/crearProducto", controllerProducto.crearProducto);
router.get("/productos", checkAuthAdmin, controllerProducto.consultarProductos);
router.get("/producto/:id", controllerProducto.consultarProducto);
router.get("/coberturas", controllerCobertura);
router.get("/tamanos", controllerTamano);
router.post("/pedidos", checkAuth, controllerPedido.crearPedido);
router.get("/pedidos", checkAuthAdmin, controllerPedido.consultarPedidos);
router.get("/pedido/:id", controllerPedido.consultarPedido);
router.get("/estadosPedido", controllerEstado);
router.get("/sabores", controllerSabor);
router.post("/cliente/login", controllerCliente.loginCliente);
router.post("/admin/login", controllerAdmin.loginAdmin);
router.post("/registroAdmin", controllerAdmin.registroAdmin);
router.put('/pedido/:id',checkAuthAdmin,controllerPedido.editarEstadoPedidobyId);
router.post('/enviarEmail', controllerEmail);
module.exports = router;
